name: Build, Push & Sign (bootc 43) + ISO (multi-arch)
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    env:
      IMAGE: ghcr.io/${{ github.repository_owner }}/chelipeds
      TAG: "43"
    steps:
      - uses: actions/checkout@v4

      - name: Compute date tag
        id: vars
        run: echo "DATE_TAG=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Install Podman + QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y podman qemu-user-static

      - name: Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      # --- Build per-arch images ---
      - name: Build amd64
        run: |
          podman build \
            --platform linux/amd64 \
            -t $IMAGE:${TAG}-amd64 \
            -t $IMAGE:${TAG}-${DATE_TAG}-amd64 \
            .

      - name: Build arm64
        run: |
          podman build \
            --platform linux/arm64 \
            -t $IMAGE:${TAG}-arm64 \
            -t $IMAGE:${TAG}-${DATE_TAG}-arm64 \
            .

      - name: Push per-arch images
        run: |
          podman push $IMAGE:${TAG}-amd64
          podman push $IMAGE:${TAG}-${DATE_TAG}-amd64
          podman push $IMAGE:${TAG}-arm64
          podman push $IMAGE:${TAG}-${DATE_TAG}-arm64

      # --- Create & push manifest lists (multi-arch) ---
      - name: Create manifest lists
        run: |
          podman manifest create $IMAGE:${TAG}
          podman manifest add $IMAGE:${TAG} $IMAGE:${TAG}-amd64
          podman manifest add $IMAGE:${TAG} $IMAGE:${TAG}-arm64

          podman manifest create $IMAGE:${TAG}-${DATE_TAG}
          podman manifest add $IMAGE:${TAG}-${DATE_TAG} $IMAGE:${TAG}-${DATE_TAG}-amd64
          podman manifest add $IMAGE:${TAG}-${DATE_TAG} $IMAGE:${TAG}-${DATE_TAG}-arm64

      - name: Push manifest lists
        run: |
          podman manifest push $IMAGE:${TAG}
          podman manifest push $IMAGE:${TAG}-${DATE_TAG}

      # --- Cosign sign both manifests recursively ---
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0

      - name: Cosign sign images (keyless)
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          cosign sign --recursive $IMAGE:${TAG}
          cosign sign --recursive $IMAGE:${TAG}-${DATE_TAG}

      # --- Build a bootable ISO (amd64 base) ---
      - name: Build bootable ISO (amd64)
        run: |
          mkdir -p output
          podman run --privileged --rm \
            -v /var/lib/containers:/var/lib/containers \
            -v ${{ github.workspace }}/output:/output \
            quay.io/centos-bootc/bootc-image-builder:latest \
            --type iso \
            --image $IMAGE:${TAG}-amd64

      # --- Sign the ISO blob ---
      - name: Cosign sign ISO
        env:
          COSIGN_EXPERIMENTAL: "1"
        run: |
          ISO=$(ls output/*.iso | head -n1)
          cosign sign-blob "$ISO" --output-signature "$ISO.sig"
          echo "Signed $ISO -> $ISO.sig"

      - name: Upload ISO + signature
        uses: actions/upload-artifact@v4
        with:
          name: chelipeds-iso-43
          path: |
            output/*.iso
            output/*.iso.sig

      # (optional) upload to Cloudflare R2
      # - name: Install rclone
      #   run: curl https://rclone.org/install.sh | sudo bash
      # - name: Upload ISO to Cloudflare R2
      #   env:
      #     RCLONE_CONFIG_R2_TYPE: s3
      #     RCLONE_CONFIG_R2_PROVIDER: Cloudflare
      #     RCLONE_CONFIG_R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
      #     RCLONE_CONFIG_R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      #     RCLONE_CONFIG_R2_ENDPOINT: https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
      #     R2_BUCKET: ${{ secrets.R2_BUCKET }}
      #   run: |
      #     rclone copy output/*.iso r2:${R2_BUCKET}/chelipeds/
      #     rclone copy output/*.iso.sig r2:${R2_BUCKET}/chelipeds/
